services:
  serena:
    image: serena:latest
    # To work with projects, you must mount them into /workspace/ in the container:
    # volumes:
      # - ./my-project:/workspace/my-project
      # - /path/to/another/project:/workspace/another-project
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    ports:
      - "${SERENA_PORT:-9121}:9121"  # MCP server port
    environment:
      - SERENA_DOCKER=1
    command:
      - "uv run --directory . serena start-mcp-server --transport sse --port 9121 --host 0.0.0.0"

